// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/screenshots/AnalyzeDocument.tsx": () => import("../components/mockups/screenshots/AnalyzeDocument.tsx"),
  "./components/mockups/screenshots/ContractReviewResult.tsx": () => import("../components/mockups/screenshots/ContractReviewResult.tsx"),
  "./components/mockups/screenshots/Dashboard.tsx": () => import("../components/mockups/screenshots/Dashboard.tsx")
};
