// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/animated-bg/AuroraMesh.tsx": () => import("../components/mockups/animated-bg/AuroraMesh.tsx"),
  "./components/mockups/animated-bg/GridPulse.tsx": () => import("../components/mockups/animated-bg/GridPulse.tsx"),
  "./components/mockups/animated-bg/ParticleFlow.tsx": () => import("../components/mockups/animated-bg/ParticleFlow.tsx")
};
